title: Siddhartha Kandpal # your name (or website title) here
logo: "/images/myself.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A recent graduate in Business Intelligence, eager to leverage my skills and knowledge in statistical analysis, data modeling, and programming, and have experience working with tools such as SQL, Python, Tableau, and Power BI.
  <br><br>
  If you're looking for a recent graduate with a strong foundation in data analysis and a passion for making an impact, let's connect. I am eager to discuss how I can bring value to your team and contribute to your organization's data analysis efforts.
  <br><br>
  <a href="https://www.linkedin.com/in/siddharthakandpal/">View my LinkedIn Profile</a> 
show_downloads: true  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson:Â '#900C3F'

